### ISSUE TITLE
week 8 ready for review

### ISSUE THREAD

**Issue by dwellons** [dwellons/DonationLog#8]
@pawaitemadisoncollege I have week 8 ready for review also! I wanted to do something on my project instead of the PetStore api. I looked at the email api's but I wanted to go over that with you before hand. I don't know what the best idea is going to be, in terms of sending a report in an email. I thought about just creating a pdf and sending that, i looked at google mail api but I don't know if I want anyone to have to log into it

I wound up using the geonames api I've used before, but I couldn't figure out how to get it to do what I wanted. I'm getting the results and everything I want, but I want the weather to just display all the time at the bottom of the sidebar or in the footer without interaction to get it, just to load when the page loads. I could not figure out how to get that to happen and spent way too long trying, I just wound up making a jsp page to display when the user clicks a link. Is that something that we can do?

**Comment by pawaitemadisoncollege** [comment]
Hi @dwellons! 

Before I forget... Javamail might be worth looking at for sending email. It's not a restful service, but it does meet the requirement of using an external library or api.

Regarding calling the service "automatically" - the way to do this would be to route through a servlet before displaying the jsp. The servlet can call your serviceDao to get the response, and then put the data you want to display in the request or session. If you put it in the session, then it would stick around and be available on every page in the application. 

You consumed two services! Wow! Great attention to best practices here by not hard-coding the details: https://github.com/dwellons/DonationLog/blob/4e211caad6515551d92310971566b9a35af71a34/src/main/java/weatherAPI/persistence/WeatherDAO.java#L36-L38. If you use LocationDao longterm - do the same thing there. 


- [ ] If you end up using this in your final code base, consider loading the properties a single time - remember how we used the application start up servlet in adv java? https://github.com/dwellons/DonationLog/blob/4e211caad6515551d92310971566b9a35af71a34/src/main/java/weatherAPI/persistence/WeatherDAO.java#L25
- [ ] I think LocationTestServiceClient and WetherTestServiceClient could be removed now that you have Daos to do this work? 

Keep up this great momentum!!

**Comment by dwellons** [comment]
@pawaitemadisoncollege I am closing this issue, I have created my App start up servlet and have the weather loading
